<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250121184844 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE classe (id INT AUTO_INCREMENT NOT NULL, class_name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE race (id INT AUTO_INCREMENT NOT NULL, race_name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survivant (id INT AUTO_INCREMENT NOT NULL, race_id INT NOT NULL, nom VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, image VARCHAR(255) NOT NULL, puissance INT NOT NULL, INDEX IDX_526EE3F36E59D40D (race_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survivant_classe (survivant_id INT NOT NULL, classe_id INT NOT NULL, INDEX IDX_F4F41F78E9AE49B (survivant_id), INDEX IDX_F4F41F788F5EA509 (classe_id), PRIMARY KEY(survivant_id, classe_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE survivant ADD CONSTRAINT FK_526EE3F36E59D40D FOREIGN KEY (race_id) REFERENCES race (id)');
        $this->addSql('ALTER TABLE survivant_classe ADD CONSTRAINT FK_F4F41F78E9AE49B FOREIGN KEY (survivant_id) REFERENCES survivant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE survivant_classe ADD CONSTRAINT FK_F4F41F788F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id) ON DELETE CASCADE');
        $this->addSql("INSERT INTO `classe` (`id`, `class_name`) VALUES
        (1, 'Mêlée'),
        (2, 'Mage'),
        (3, 'Archer'),
        (4, 'Protecteur'),
        (5, 'Soutient'),
        (6, 'Puissant'),
        (7, 'Agile');");
        $this->addSql("INSERT INTO `race` (`id`, `race_name`) VALUES
        (1, 'Humain'),
        (2, 'Elfe'),
        (3, 'Nain'),
        (4, 'Géant'),
        (5, 'Orc'),
        (6, 'Homme-poisson'),
        (7, 'Cosmocat'),
        (8, 'Mutant');");
        $this->addSql("INSERT INTO `survivant` (`id`, `nom`, `description`, `image`, `race_id`, `puissance`) VALUES
(1, 'Ann', '<div><em>“Des zombies ? Bah ! Ils ne valent rien face à un vrai prédateur !”<br></em><br></div><div>Il y a de nombreuses années, Ann fut la seule à échapper au massacre de son village, victime des déprédations du seigneur local. Elle s’enfuit dans la forêt où elle fut recueillie, affamée et transie, par un groupe de chasseurs barbares. Elle était trop jeune pour les accompagner, aussi la placèrent-ils dans un couvent à proximité. Elle y grandit et affûta ses talents de survie, aussi bien en étudiant dans la bibliothèque du couvent qu’au cours de longues expéditions dans les régions sauvages. Le temps passant, la région n’eut plus aucun secret pour elle. Aujourd’hui, suite à l’invasion des zombies, elle retourne vers la civilisation dans le but de chasser cette proie hors du commun.</div>', 'fAnn.jpg', 1, 20),
(2, 'Ariane', '<div><em>“Et alors ? Elle est où la milice, maintenant ?”<br></em><br></div><div>Orpheline des rues, Ariane dut rapidement apprendre à devenir agile, coriace et habile afin de garder une longueur d’avance sur les hommes d’armes de la milice. Elle finit par rejoindre différentes Guildes, travaillant souvent pour plusieurs d’entre elles à la fois. Sa dernière mission fut celle qu’elle regretta amèrement d’avoir acceptée. On l’engagea pour voler les clés de la ville, détenues par le maire en personne. Mais hélas, son commanditaire s’avéra être un nécromancien. Elle parvint toutefois à échapper à ses griffes et survécu à l’invasion. À présent, elle propose son aide à tous ceux qui sont prêts à se dresser contre la terrible menace. Personne n’a jamais percé son terrible petit secret… du moins jusqu’ici.</div>', 'fAriane.webp', 1, 25),
(3, 'Asmin', '<div><em>“Mon nom est… Oh, aucune importance, appelez-moi Asim.”<br></em><br></div><div>Asim était un marchand téméraire, à la recherche de nouvelles contrées à explorer, de nouvelles amitiés, et d’opportunités commerciales. Sept ans ont suffi à ce que son nom soit reconnu. Puis, le sultan l’a appelé et choisi pour être son émissaire dans les contrées glaciales du nord. Homme pragmatique, Asim est resté quand les orques sont arrivés, et il a vendu toutes ses armes avec un énorme rabais. A la surprise générale, il s’est révélé un épéiste expérimenté et à bientôt rejoins un groupe solide de survivants. Pourra-t-il revenir à sa terre natale le plus tôt possible ? Il n’est pas certain. Face à la Mort, il a trouvé un autre sens à sa vie.</div>', 'fAsim.jpg', 1, 19),
(4, 'Baldric', '<div><em>“Le savoir est source de pouvoir. La magie n’est qu’un outil.”<br></em><br></div><div>Baldric était un aventurier hors pair. Il était fort, mystérieux, puissant et ses pouvoirs magiques étaient devenus légendaires. À ses yeux pourtant, la recherche et le savoir avaient toujours primé sur les prouesses magiques. L’art de choisir le sortilège idéal en toute situation lui avait toujours procuré un avantage, ce qui lui avait permis d’atteindre un âge avancé. Il continuait à prêcher cette doctrine au sein de son académie de magie, en dépit des critiques acerbes de ses pairs, pour qui les connaissances des arcanes devaient rester « occultes » et secrètes. L’invasion de la horde allait changer tout ça. Aujourd’hui, il se rend là où on a besoin de lui, il enseigne à tous ceux qui sont désireux d’apprendre et désintègre le premier zombie qui pointe le bout de son nez.</div>', 'fBaldric.jpg', 1, 35),
(5, 'Berin', '<div><em>“J’emmène toujours ma Hache Enchantée de Crochetage Tonitruant, au cas où.”<br></em><br></div><div>Aventurier dans l’âme, Berin a cherché la gloire, la fortune et des ennuis toute sa vie. Ce qu’il aime le plus est de crapahuter dans les donjons : brutaliser des monstres est son passe-temps favori. Quand le seigneur local lui a demandé de combattre les orques pour la fortune et la gloire, Berin est parti bille en tête, et a gagné. En tout cas, jusqu’au jour où son groupe rencontra les premiers orques zombies. Ils ont perdu le prêtre dans la bataille qui s’ensuivit, et cherchèrent à se venger. Ils tuèrent leur premier nécromancien, mais perdirent une autre amie, et se jurèrent de la venger elle-aussi… Quelques semaines plus tard, Berin était le seul survivant. Un groupe de survivant le trouva et lui proposa de les rejoindre. Le monde est maintenant un gigantesque donjon, et il y a des monstres à brutaliser partout !</div>', 'fBerin.jpg', 3, 32),
(6, 'Clovis', '<div><em>“La fin du monde ? De ton monde, peut-être. Pas du mien.”<br></em><br></div><div>L’amour de la justice poussa Clovis à devenir paladin, il y a fort longtemps. Au fil des ans, il apprit à ses dépens que rien n’est jamais ni tout noir ni tout blanc. Des nuances de gris entachèrent sa perception de la justice, particulièrement suite aux actes qu’il dut accomplir pour que son seigneur garde les mains propres. Aujourd’hui, la civilisation s’effondre et les puissants ne pensent qu’à leur propre sécurité. Clovis a réalisé que la justice et la gloire représentent bien plus qu’un bouclier brillant ou qu’un serment de fidélité. L’honneur, le vrai, se gagne par les actes, et non pas par décret de noblesse.</div>', 'fClovis.jpg', 1, 30),
(7, 'Doran', '<div><em>“Pourquoi l’épée ? Les épées n’ont pas besoin d’être rechargées.”<br></em><br></div><div>Autrefois mage de bataille dans l’armée royale, Doran se bat aujourd’hui avec ce qu’il reste de l’humanité, pour la survie. Bien que Doran puisse invoquer des sortilèges aux côtés des meilleurs magiciens, il préfère son épée pour le combat rapproché. Il a appris la valeur d’une lame bien aiguisée au cours de la guerre contre les orques, notamment lorsque la bataille dure, que l’esprit fatigue et que jeter de sortilèges réclame un effort herculéen. Un bras armé se fatigue lui aussi, mais l’adrénaline est plus efficace que la magie pour bander les muscles. Doran est toujours prêt à enseigner un peu de magie contre une leçon d’escrime.</div>', 'fDoran.jpg', 1, 29),
(8, 'Johannes', '<div><em>“Comment fonctionne ma dernière invention, dis-tu ? Je n’en suis pas sûr. Tiens, prends là !”<br></em><br></div><div>Johannes est trop humble et introverti pour l’admettre, mais il est l’un des plus brillants ingénieurs de cet âge sombre. Sa langue maternelle est la science. Avec le parrainage bienveillant du Roi, ses inventions rendirent la vie plus simple aux gens. Il se fit aussi beaucoup d’ennemis : l’église voyait l’influence du Démon dans son travail. Une situation embarrassante, surtout si l’on considère que Johannes peut transformer des objets banals en armes et en merveilles, sans que personne, y compris lui-même, ne puissent donner d’explications adéquates.<br><br></div><div>Quand l’armée royale, menée par le Roi lui-même, fut défaite, l’inventeur laissa sa vie derrière lui et devint un survivant. Sans personne pour jeter un œil suspicieux à son travail, Johannes tire désormais pleinement parti de ses capacités, et s’avère être un atout crucial pour toute la communauté.</div>', 'fJohannes.jpg', 1, 25),
(9, 'Kabral', '<div><em>“J’ai les manières de ma mère. J’ai également la tronche de mon père. C’est dans mes gènes.”<br></em><br></div><div>Kabral a grandi dans une ferme lointaine, l’une des premières touchées par la Horde Verte. Sa mère l’a élevé comme un humain, ne connaissant pas vraiment les traditions orques. Lorsqu’elle est morte, il resta à la ferme et en devint un précieux atout, non seulement grâce à sa force et à sa vigueur, mais aussi grâce à ses talents naturels de guerrier. Quand la Horde Verte a déferlé, cette fois-ci sous forme de zombies, la défense valeureuse de Kabral permit à la plupart des habitants de s’échapper dans une relative sécurité.</div>', 'fKabral.jpg', 5, 40),
(10, 'Karl', '<div><em>“Tout le monde peut apprendre à maîtriser ça, tu sais. Ce n’est pas l’apanage d’une élite.”<br></em><br></div><div>Karl est un ancien officier du génie, un vétéran endurci de nombreuses batailles. Il a souvent travaillé en étroite collaboration avec les mages de siège du Roi, ce qui lui a permis d’apprendre que derrière le mysticisme et les rituels se dissimulent des théorèmes et des lois arcaniques. La magie est une science ! Son point de vue peu orthodoxe, couplé à son insolente réussite, lui a presque valu d’être emprisonné. Mais pendant l’invasion, alors que les zombies envahissaient les rues, il fallut faire appel à quiconque était capable d’utiliser le mana pour conjurer des flammes. Aujourd’hui, il est persuadé que la seule chance de survie de l’humanité en cet Âge de Ténèbres réside dans la propagation de sa doctrine.</div>', 'fKarl.webp', 1, 30),
(11, 'Morrigan', '<div><em>“Des coups bas, tu dis ? Laisse-moi t’expliquer la différence entre la vie et la mort.”<br></em><br></div><div>En tant que garde du corps de l’ambassadeur Elfe Noir à Wulfsburg, Morrigan a toujours vécu dans la paranoïa. Son peuple est considéré, dans le meilleur des cas, avec méfiance, et la menace de tentatives d’assassinat plane en permanence sur ses ressortissants. Professionnelle avisée, elle sait que la fuite face à un adversaire supérieur n’est pas un signe de lâcheté. Un avis que ne partageait hélas pas l’ambassadeur, qui a choisi de rester combattre la horde zombie. Morrigan est la seule survivante. Expatriée et déshonorée par la mort de l’ambassadeur, Morrigan commence une nouvelle vie, où ses nouveaux compagnons ne la jugent pas sur d’anciennes rancœurs et apprécient les conseils judicieux et la maîtrise martiale de ce vétéran de talent.</div>', 'fMorrigan.jpg', 2, 20),
(12, 'Nelly', '<div><em>“La vie et le risque marchent main dans la main, mon ami.”<br></em><br></div><div>La chance n’avait jamais vraiment souri à Nelly, qui se retrouva coincée comme serveuse de taverne dès son plus jeune âge. Elle réussit à éviter les pièges les plus courants qui attendent les jeunes filles, comme devenir la maîtresse de quelque nobliau ou échouer dans un bordel. Rêveuse invétérée, Nelly attendait plus de la vie, sans vraiment savoir quoi, ou comment l’obtenir. Jusqu’à ce que viennent les zombies. Il se trouve que cogner des soûlards aux mains baladeuses à coup de chopes pleines n’est pas si différent que de tabasser des zombies trop collants à coup de massue. Naturellement douée avec n’importe quelle arme, Nelly a découvert son but dans la vie : le Zombicide !</div>', 'fNelly.jpg', 1, 18),
(13, 'Rolf', '<div><em>“Les orcs étaient mes ennemis, mais des ennemis honorables. Les nécromanciens méritent une mort infamante.”<br></em><br></div><div>Trop impulsif&nbsp; pour être un bon fermier mais trop désobéissant pour être un bon soldat, Rolf choisit la voie des chasseurs d’orques. Avec d’autres têtes brûlées, il a patrouillé au-delà de la frontière avec les territoires orques pour empêcher les raids et punir les intrus. Evidemment, la vie des chasseurs d’orques était supposée être courte. Rolf, pourtant, se montra assez talentueux et chanceux pour survivre à quelques batailles et en apprendre plus sur ses ennemis. A plus d’un titre, il se sentit plus proche des orques sauvages et assoiffés de sang, que des humains traîtres et lâches.<br><br></div><div>Rolf assista aux premières loges à l’invasion orque, puis à l’infection des nécromanciens. Conduit par la haine, il survécut aux deux et fut bientôt le seul chasseur d’orques vivant de la région. Rolf compte maintenant parmi les guerriers les plus puissants des environs, et sa connaissance des contrées orques est inestimable. Le jeune homme, en revanche, est aveuglé par sa soif de sang et se montre infatigable dans sa quête meurtrière.</div>', 'fRolf.jpg', 1, 25),
(14, 'Katelyn', '<div><em>“Une arme pour chaque occasion.”<br></em><br></div><div>On pourrait penser que Katelyn emmène un peu trop d’armes dans sa lutte contre la Horde Verte, mais finalement, elle arrive toujours à toutes les utiliser dans chacun de ses combats. Un arc pour le combat à distance, des épées longues pour les espaces ouverts, des épées courtes en milieu confiné, et autant de dagues qu’elle peut n emporter. Avant que la Peste Zombie ne frappe la Horde Verte, elle était apprentie armurière, et quand l’armée a été mise en pièces, les villes et les villages ravagés, elle et son maître emmenèrent tout ce qu’ils pouvaient prendre. Hélas, son maître n’a pas survécu, et maintenant elle transporte son fardeau toute seule.</div>', 'fKatelyn.jpg', 1, 32),
(15, 'Megan', '<div><em>“Le savoir est une force. Est-ce que les orques cachent leur force ? Non. Donc, laissez-moi vous montrer comment fonctionne le savoir.”<br></em><br></div><div>Héritière d’une famille de voleurs, Megan montra un esprit remarquable dès son plus jeune âge, associé à une inextinguible soif d’apprendre. Elle décida de devenir magicien et, avec le soutien de la guilde familiale, eut accès à toutes sortes de livres. Quand le temps fut venu, la jeune femme choisit une vie aventureuse et devint un mercenaire unique en son genre. Au bout d’un certain temps, Megan désira la connaissance et le pouvoir pour elle-même : elle cherchait un ancien tumulus funéraire loin dans les terres orques quand les zombies arrivèrent.<br><br></div><div>Sage avant l’heure, Megan sait qu’elle pourrait être tentée par la magie noire. Ce n’est pas le destin qu’elle recherche, toutefois, alors elle cherche des survivants pour l’aider à éradiquer la menace nécromancienne. Megan est brillante, et ne craint personne… à part sa propre tentation.</div>', 'fMegan.jpg', 1, 22),
(16, 'Samson', '<div><em>“Reculez les gars. C’est un boulot pour un nain.”<br></em><br></div><div>Samson trouve la vision qu’ont les humains de l’artisanat Nain particulièrement pittoresque. Le métal est le même, la conception similaire (ou presque), mais ajoutez quelques runes Naines sur une épée ou un marteau et les humains penseront que c’est de la magie ! Ces armes seront plus précises, plus puissantes et plus durables. Samson s’est fait un joli paquet en vendant ses armes « Naines », bien qu’il n’ait jamais trompé quiconque sur la marchandise. Il était simplement un forgeron très compétent qui se trouvait être aussi un Nain. À présent que l’apocalypse zombie se déchaîne, il est heureux de pouvoir « améliorer » les armes qui passent entre ses mains avec sa « touche Naine ».</div>', 'fSamson.jpg', 3, 33),
(17, 'Seli', '<div><em>“On…on s’est rencontré avant ? Vous me rappelez quelqu’un… J’ai tenté de vous tuer ?”<br></em><br></div><div>Des survivants ont découvert Seli, inconsciente au milieu de cadavres, après une bataille acharnée contre une horde zombie. Au début, tout le monde pensa que la guerrière elfe avait pris un mauvais coup sur la tête et avait perdu la mémoire. En fait, c’était pire : pour une raison inconnue, Seli est incapable de se souvenir des choses plus de quelques jours. Jusqu’à présent, nul ne sait si c’est une malédiction, une blessure permanente ou autre chose… La guerrière elfe a cependant conservé ses exceptionnelles capacités martiales, et s’avère être une athlète époustouflante, doublée d’une assassin habile. Son tempérament joyeux et son sens de l’humour peuvent être tristes à voir, hélas. Tous les deux jours, Seli se réveille au milieu d’étrangers, sans aucun souvenir de son passé, dans un monde ravagé… Qui est-elle vraiment ?</div>', 'fSeli.jpg', 2, 22),
(18, 'Silas', '<div><em>“Les zombies sont une insulte à la vie et à la beauté. Je suis là pour rectifier le tir.”<br></em><br></div><div>Les Elfes vivent très longtemps… jusqu’à ce qu’ils soient massacrés par des zombies. C’est quelque chose que Silas s’est efforcé de faire entrer dans le crâne des seigneurs Elfiques, dès que sont parvenues les premières rumeurs sur les nécromanciens qui levaient des hordes au cœur des forêts les plus sombres. Silas pensait qu’il fallait agir, et vite. Mais les Elfes mesurent leur vie en siècles, et non en décennies. Le débat visant à établir quelle serait la réponse appropriée pourrait bien durer des années. Cela ne convient pas à Silas. Il a décidé de faire du combat contre la horde une affaire personnelle, d’essayer de répandre le bien dans le monde et de tenter de sauver quelques vies au passage. Ce n’est qu’en s’unissant que les races des peuples libres peuvent espérer repousser la marée de la non-vie.</div>', 'fSilas.jpg', 2, 20),
(19, 'Solveig', '<div><em>“Les légendes de ma contrée parlent de +ceux qui choisissent les morts+. Que feraient-ils de la horde zombie ? Je me le demande.”<br></em><br></div><div>Solveig était un caravaniere, qui voyageait vers le sud depuis sa province natale. Sa cargaison était largement composée de vêtements, d’outils, d’hydromel bien conservé, mais plus important encore, d’armes et d’armures. Elle avait entendu parler de la guerre contre les peaux vertes, et fut soulagée quand sa caravane bien protégée parvint à la capitale. Malheureusement, avant qu’elle ne puisse rentrer chez elle, la peste zombie frappa, et l’argent perdit soudainement toute valeur. Comme tout le monde, Solveig était entraînée au combat, au maniement de l’épée et du bouclier. Elle ne pensait pas en avoir besoin un jour mais tout a changé.</div>', 'fSolveig.jpg', 1, 39),
(20, 'Théo', '<div><em>“Je suis venu pour le peuple. Les cités ne sont que corruption.”<br></em><br></div><div>Théo est un rôdeur, survivant dans les bois à l’écart des villes grâce à ses talents et à sa ruse. L’apparition des Zombie Wolfz, en quête de massacres plutôt que de nourriture, a été le premier indice qu’une force maléfique était à l’œuvre. Quelque chose de terrible avait frappé Wulfsburg et il appartenait à Théo de découvrir la vérité en se rendant sur place. Il a aujourd’hui entrepris une nouvelle quête : trouver un remède contre la peste zombie et empêcher la corruption de se répandre dans les forêts qu’il défend.</div>', 'fTheo.webp', 1, 27),
(21, 'Cardinal Birmbauer', '<div><em>“Je crois que le pouvoir des dieux peut inciter les gens à faire des choses terribles, tout comme je crois que le canon de mon arme peut les inciter à rentrer dans le droit chemin.”<br></em><br></div><div>Le cardinal Reginal Birmbauer était autrefois le prêtre de la petite église de son quartier. Il mit un terme à sa vie de piété quand la déesse qu’il adorait l’abandonna au moment où il avait besoin d’elle : le temple bâti de ses propres mains fut anéanti par des vers géants venus de l’espace. Déterminé à changer de vie et à avoir un impact sur le monde, Reginald exhuma son vieux tromblon runique et rejoignit la résistance pour combattre les forces du mal qui se répandait à travers la Grande Cité de Gateway. Il est expert en balistique et un érudit hors-pair en théologie.</div>', 'fBirmbauer.jpg', 6, 10),
(22, 'Kendra', '<div><em>“Les chefs de notre grande cité se sont fourvoyés. Je ne peux rester de marbre alors que nos sorciers sont déportés en prison, ou pire. Le temps d’une désobéissance vengeresse est venu !”<br></em><br></div><div>Ancien officier de la Garde de la Cité de Gateway, la loyauté de Kendra changea de camp lorsqu’elle ne put davantage, en toute conscience, exécuter les ordres du Chancelier et des Inquisiteurs dont l’unique objectif était d’écraser la Révolte de Sorciers. Kendra était réputée pour son rôle important dans la fuite de la horde Drueggar hors de la cité, une cause qu’elle croyait juste et noble. Mais quand ses talents furent reconnus par ses supérieurs, elle se vit confier de nouvelles tâches relatives à la traque des résistants. La limite fut franchie quand elle fut forcée d’arrêter un ami d’enfance et d’assister à son exécution. Depuis, elle a juré de se battre uniquement pour la résistance.</div>', 'fKendra.jpg', 1, 18),
(23, 'Spellbones', '<div><em>“Finissons-en vite avec ces histoires de révolution, que je puisse me remettre au travail. Les os ne parlent pas à n’importe qui, vous savez ?”</em></div><div><br>La paléomancie est l’étude des os anciens, et la faculté d’en tirer une puissante magie. De nos jours, Tak Trooblood est peut-être le plus accompli et le plus célèbre des pratiquants de ce type de magie. Faisant appel à ses vastes connaissances en matière d’espèces animales disparues, et tirant profit de son impressionnante collection d’os anciens, Tak peut invoquer la puissance de mystérieuses créatures magiques qui parcouraient autrefois le Monde Connu. Les autorités de Gateway l’ont déclaré hérétique et l’ont forcé à fermer les portes de son cher Musée des Bêtes Magiques. Peu après, Tak pris le maquis et rejoignit la résistance.</div>', 'fSpellbones.jpg', 1, 9),
(24, 'Kirag (et Thorg)', '<div><strong>Ce personnage se joue obligatoirement avec Thorg et se deplace obligatoirement avec lui</strong><br><br><em>“Attention à vos mains en vous approchant d’lui. Y’mord.”<br></em><br></div><div>Les nains du clan de Kirag avaient la sinistre réputation d’être les meilleurs pillards des terres de l’ouest. Ils étaient maîtres en techniques de guérilla et en frappes-éclairs sur des villages qui n’auraient jamais cru que des nains puissent dresser et conduire leurs montures aussi efficacement. Les loups géants étaient communs, les chevaux un peu moins, puis venaient les sangliers géants, et ainsi de suite. Pourtant, aucune monture n’était aussi exotique que Thorg, celle de Kirag. Ils l’avaient trouvé dans la tour d’un magicien. Thorg était manifestement une sorte d’ogre, mais avait été croisé avec toutes sortes de choses étranges. Kirag et Thorg forment pourtant un duo inséparable, et sont de puissants guerriers face à la peste noire.</div>', 'fKirag-Thorg.jpg', 3, 22),
(25, 'Thorg (et Kirag)', '<div><strong>Ce personnage se joue obligatoirement avec Kirag, Kirag se déplacera obligatoirement avec lui<br></strong><br><em>“Attention à vos mains en vous approchant d’lui. Y’mord.”<br></em><br></div><div>Les nains du clan de Kirag avaient la sinistre réputation d’être les meilleurs pillards des terres de l’ouest. Ils étaient maîtres en techniques de guérilla et en frappes-éclairs sur des villages qui n’auraient jamais cru que des nains puissent dresser et conduire leurs montures aussi efficacement. Les loups géants étaient communs, les chevaux un peu moins, puis venaient les sangliers géants, et ainsi de suite. Pourtant, aucune monture n’était aussi exotique que Thorg, celle de Kirag. Ils l’avaient trouvé dans la tour d’un magicien. Thorg était manifestement une sorte d’ogre, mais avait été croisé avec toutes sortes de choses étranges. Kirag et Thorg forment pourtant un duo inséparable, et sont de puissants guerriers face à la peste noire.</div>', 'fKirag-Thorg.jpg', 4, 42),
(26, 'Tola', '<div><em>“Zvieil choz c’est nib. Trouvera’ pod’gob por l’graillon.”<br></em><br></div><div>Alors qu’autrefois il les aurait volontiers massacrés pour leurs biens, Tola combat aujourd’hui aux côtés des survivants contre la horde verte. Pour le camp des survivants, la présence d’un renégat orque est bienvenue. Ils aimeraient juste réussir à comprendre tout ce qu’il dit. Sa diction du commun est inconnue dans l’ouest, et bien que ses paroles ressemblent au commun, elles ne sont pas mises dans le bon ordre. Tola lui-même ne voit inconvénient à se battre des jours entiers, si ce n’est qu’il n’y pas tout le temps de quoi manger à sa faim.</div>', 'fTola.jpg', 5, 41),
(27, 'Carol', '<div><em>“Ces âmes misérables ne méritaient pas ça. Pas même les orques.”<br></em><br></div><div>Femme très croyante, Carol Noirchêne trouve la peste noire particulièrement maléfique. Pas seulement parce que l’infection a tué sans compter, mais parce que les âmes pourraient bien être prisonnières de ces carcasses zombies. Les magiciens et les prêtres survivants n’apportent aucune réponse, car la réanimation pourrait être le fruit de nombreuses énergies néfastes. Carol ne prendra aucun risque. Libérer ces âmes errantes enfermées dans des carcasses pourrissantes est sa juste cause, tout comme envoyer les responsables brûler en enfer !</div>', 'fCarol.jpg', 1, 40),
(28, 'Genevieve', '<div><em>“Très bien. Vous avez jusqu’à trois pour me prouver que vous respirez toujours. Un… deux…”<br></em><br></div><div>Geneviève ne se laisse marcher sur les pieds par personne. Quand les zombies attaquèrent son foyer au beau milieu de la nuit, elle les tint à distance en robe de nuit. Maintenant qu’elle porte son armure et qu’elle est bien armée, il faudrait un engin de siège pour l’arrêter. Geneviève est une tireuse d’élite avec son arbalète. Elle peut abattre un homme, un ours ou un zombie à cinquante mètres. Et si quelqu’un s’avise de s’approcher trop près, on dit qu’elle décapite net n’importe qui à la machette. Geneviève est ici pour gagner la guerre.</div>', 'fGenevieve.jpg', 1, 39),
(29, 'Mizar', '<div><em>“Il y a un mandat pour cela. Il y a un mandat pour chaque chose importante. Mais il y a aussi une faux, pour tout ce qui ne mérite pas de mandat.”</em></div><div><br>L’Inquisiteur Mizar en connaît un rayon sur la mort, les mourants, et les morts-vivants. Son ordre a étudié la nécromancie – dans le but de l’éradiquer – depuis bien plus longtemps que les quelques nécromanciens qui rôdent dans les parages. Ils connaissent tous les secrets. Ils connaissent tous les rites. Et ils apporteront une mort bénie et digne à tout ce que doit mourir. Par sa faux et sa volonté, par ses prières et ses rites, l’Inquisiteur Mizar portera la mort partout où elle est requise, et la repoussera partout où elle n’est pas le bienvenue.</div>', 'fMizard.jpg', 1, 9),
(30, 'Klom', '<div><em>“Viens ici si tu l’oses.”<br></em><br></div><div>Klom ne craint pas les zombies. Il n’a peur de rien, à part des araignées, mais ça il ne le dira jamais. C’est déjà un coriace, un combattant et un bandit bien avant que les zombies ne submergent son campement. Il se bat contre ces pénibles depuis leur arrivée. Armé de son fléau, Klom peut abattre à peu près n’importe quoi. Et si ça ne suffit pas, il les piétinera. Il a déjà pris quelques trophées, mais les autres ont tendance à se plaindre au sujet des têtes de zombies coupées. Peut-être que les doigts les dérangeraient moins ?</div>', 'fKlom.jpg', 4, 48),
(31, 'Lord Bazak', '<div><em>“En avant ! En avant vers la victoire ! En avant, pour toujours !”<br></em><br></div><div>Lord Bazak est parti pour une guerre longue. Il en sait long, ou du moins connaît-il les rumeurs, sur quelques plaisanteries des nécromanciens, et il sait qu’ils ne seront pas vaincus facilement. Il a été témoin de ce que les zombies peuvent faire. Bazak et les siens sont parvenus à les repousser quand ils ont attaqué ses terres, mais au prix de nombreuses vies, et plus chèrement encore quand ces morts se sont relevés en tant que morts-vivants. Lord Bazak et ses hommes envisagent de traverser le pays comme une lame, fauchant les nécromanciens et les zombies jusqu’au dernier.</div>', 'fBazak.jpg', 3, 39),
(32, 'Antha', '<div><em>“J’ai eu une vision de tes actes.”<br></em><br></div><div>Antha est née avec le don de double vue. Dès son plus jeune âge, elle a développé sa vision et sa capacité à se connecter à l’Autremonde. Elle a vu venir le péril zombie et a entrevu toutes les voies où cela pouvait mener. Quelques-unes d’entre elles n’aboutissent qu’au sang, aux larmes et à la mort. Aujourd’hui, Antha a quitté sa maison pour condamner ces voies, tout en sachant que le simple fait de s’impliquer en modifie certaines. Mais il y en reste tant de sombres.</div>', 'fAntha.jpg', 1, 12),
(33, 'Lady Grimm', '<div><em>“Allez !”<br></em><br></div><div>Tout le monde l’appelle Lady Grimm : les autres chevaliers, les paysans, son souverain. Personne ne lui a demandé son nom, et elle n’a pas non plus songé à le leur dire. D’ailleurs, elle ne dit quasiment rien, n’entreprend quasiment rien. Depuis le jour où elle a débarqué au fort, à demi noyée et ne portant qu’une veste militaire en piteux état, son œil et son visage marqué d’une vilaine balafre, elle est restée silencieuse, mystérieuse. Mais elle s’est également montrée féroce, la plus puissante défenseuse du fort, la première au combat. Une fois qu’elle les a frappés avec son marteau de guerre, les zombies ne bougent plus, et ne se relèvent plus jamais.</div>', 'fGrim.jpg', 1, 40),
(34, 'Cadence', '<div><em>“Vous avez ruiné ma vie. Je vais détruire la vôtre !”<br></em><br></div><div>Cadence n’avait pas l’intention de devenir sauvage. Quand sa famille a été balayée par les nécromanciens, tout ce qui lui importait était de se réfugier dans les bois pour un jour ou deux. Elle savait tirer, comme toute fille de chasseur qui se respecte, et savait comment survivre dans les bois. Leur père le leur avait appris à tous, aux filles comme aux garçons. Seulement maintenant, il ne reste plus personne à part Cadence, le bébé de la famille. Elle a vécu dans la forêt pendant des mois, à s’entraîner à tirer, à rassembler ses esprits. A présent, elle est prête à se venger.</div>', 'fCadence.jpg', 1, 16),
(35, 'Rodney le bourreau', '<div><em>“Eh, un dernier mot avant de mourir ? Hé hé !”<br></em><br></div><div>Il y aura toujours des criminels à exécuter, et la hache de Rodney Le Bourreau sera toujours prête. Toujours, enfin, sauf quand le fléau zombie pénètre au cœur des villes, emportant indifféremment les criminels comme les gens bien, menaçant la survie même de l’humanité et, pire encore, menaçant la stabilité de l’emploi de Rodney. Pour le moment, il s’est reconverti en tueur de zombies. Le mouvement de hache est légèrement différent, les résultats un peu plus salissants, mais sa cagoule était déjà rouge avant. Et ce n’est pas le sang d’une centaine ou d’un millier de zombies qui va la rendre encore plus rouge – ou ses mains plus sales.</div>', 'fRodney.jpg', 1, 33),
(36, 'Anton Guffen', '<div><em>\"\'Non, ce n\'est pas en fer. Vois-tu de la rouille ?\"</em><br><br>Anton Guffen est sans doute l\'enchanteur le plus brillant de sa civilisation. Il s\'est spécialisé dans tout, des vêtements autonettoyants aux armes à manier soi-même en passant par les boulons de baliste et les projectiles explosifs. Ses enchantements armés ont mené le royaume à de nombreuses victoires et ont fait d\'Anton un homme très riche. La Tour Guffen rivalisait même avec celle du roi en termes de hauteur et de splendeur. La horde verte a tout changé. Désormais, Anton revêt sa plus belle création, une armure enchantée aux capacités incroyables qui fait de lui quasiment une armée à lui tout seul. Dans la bataille contre la peste noire, il en aura besoin.</div>', 'fAnton.jpg', 1, 29),
(37, 'Asmodeus', '<div><em>\"L\'Assonance agace abondamment les artistes archaïques.\"</em><br><br>Autrefois connu pour ses pièces et ses poèmes imaginatifs, le barde appelé Asmodeus a tourné son esprit barbelé vers la horde verte avec passion. Ce n\'est pas que les zombies comprennent ses paroles en combat, mais elles possèdent une cadence et un débit qui attirent ses compagnons de survie, leur permettant de se battre presque tous ensemble. Asmodeus n\'est jamais vu sans son masque souriant, et la rumeur veut qu\'il ait été horriblement défiguré dans les premiers jours de la peste noire. Lorsqu\'on lui pose la question, Asmodeus lui-même se contente de sourire et reste, comme toujours, une énigme.</div>', 'fAsmodeus.jpg', 1, 22),
(38, 'Badger Brummuin', '<div>\"\'Agacé est mon état naturel, mon gars.\"<br><br>Il n\'est pas surprenant que pour un peuple qui fait de la brasserie son art suprême, la bagarre arrive en seconde position. Si tous les hommes, femmes et enfants nains savent donner un bon coup de poing, les bagarreurs professionnels portent ce passe-temps national à de nouveaux sommets. Badger\' Brummuin s\'est fait un nom lors de bagarres officielles dans les villes et villages des profondeurs naines. Puis les zombies sont arrivés. Les zombies de rang lui posent peu de problèmes, et les zombies orcs à peine plus. Son véritable plaisir est de se battre, nain contre monstre, avec des abominations. Comme son homonyme, il n\'y a pas d\'ennemi trop grand pour être combattu.</div>', 'fBadger.jpg', 3, 39),
(39, 'Billy', '<div><em>\"J\'ai toujours plaisanté sur le fait de quitter le pays. Ce n\'est pas comme ça que je l\'imaginais.\"</em><br><br>Bien qu\'il soit très jeune, l\'habileté de Billy avec son bouclier et son étoile du matin est indéniable, et lorsqu\'il s\'agit de protéger ses amis, sa bravoure ne connaît aucune limite. Aucun des membres du petit groupe n\'était né noble, mais tous vivaient à proximité des terres de leur seigneur. Si le seigneur lui-même est un comte juste et respectable, son fils est une brute notoire qui croise trop souvent la route de Billy et de ses amis. Plus d\'une fois, Billy s\'est interposé entre ses amis et le danger, et maintenant cette habitude est naturelle.</div>', 'fBilly.jpg', 1, 15),
(40, 'Brannog Steelfeet', '<div><em>\"Roi\" ? Roi de quoi ? Il n\'y a plus rien à faire pour être roi !\"</em><br><br>Brannog Steelgreaves était autrefois le seigneur et le roi d\'une puissante cité-état naine située sous la Montagne Etrangère. Son règne était aussi pacifique qu\'un gouvernement nain peut l\'être (seulement quatre guerres en vingt ans au lieu d\'une douzaine), et il était considéré comme l\'un des rois les plus sages et les plus bienveillants que l\'espèce naine ait jamais connu. Pourtant, lorsque la peste noire a frappé, leur petit royaume a été pris complètement au dépourvu. Du jour au lendemain, la Montagne Etrangère fut noyée sous la horde verte, et le roi Brannog et sa famille furent contraints de fuir. Aujourd\'hui, il rend la monnaie de sa pièce aux orcs, un crâne écrasé à la fois.</div>', 'fBrannog.jpg', 3, 30),
(41, 'Lord Brix Moonshine', '<div><em>\"Ares et moi vous apportons des nouvelles du royaume des elfes ! ... Ares ? Mon ami. L\'araignée géante qui se tient juste là. Pourquoi vous, les humains, ne le voyez jamais ?\"</em><br><br>Le Seigneur Brix a longtemps servi de liaison entre les royaumes de l\'ouest et les cours elfiques. Lorsque la horde verte a commencé ses guerres pour de bon, Lord Brix est retourné sur sa terre natale pour demander un soutien fort à leurs alliés humains. Lors d\'une embuscade tendue par des orcs porteurs de la peste, Lord Brix est le seul survivant et souffre d\'une grave commotion cérébrale. Bien que ses facultés semblent intactes, il parle et fait constamment référence à une araignée géante qu\'il nomme \"Ares\". Bien que la magie d\'invisibilité ne soit pas inconnue, il semblerait qu\'Ares ne soit qu\'une invention de l\'imagination de Lord Brix. C\'est peut-être une bonne chose, car la dernière chose dont on ait besoin, en plus de la peste noire, c\'est d\'une infestation d\'araignées géantes et invisibles !</div>', 'fBrix.jpg', 2, 28),
(42, 'Cassius', '<div><em>\"Les zombies sanglants n\'apprécient pas du tout mon sens du spectacle.\"</em><br><br>Les foules rugissantes et l\'adoration sans fin ont poussé Cassius à réaliser de grands exploits dans les fosses de combat. Sa victoire contre les Sept Chiens (des hommes qui portaient des masques de chiens et se battaient en meute) est encore évoquée avec enthousiasme par les survivants qui ont assisté à cette journée. Pourtant, il trouve que ses talents sont quelque peu gaspillés de nos jours. Les foules ont disparu, remplacées par des hordes ambulantes. Il y a toujours beaucoup de combats et de sang, bien sûr, mais les zombies n\'applaudissent pas et ne lancent certainement pas de roses. Cassius ne souhaite rien d\'autre que de les éradiquer tous, afin de retrouver sa place dans l\'arène.</div>', 'fCassius.jpg', 1, 28),
(43, 'The Deathmaster', '<div><em>\"Rien ne me fait plus plaisir que de travailler avec ma hache.\"</em><br><br>Le nom du Deathmaster est clairement une affectation, mais peu de gens peuvent le faire passer sans avoir l\'air ridicule. Il suffit de le voir en action pour comprendre que ce n\'est pas une vantardise. Le Deathmaster est venu sur ces terres à la recherche d\'une nouvelle musique, ce qui est assez étrange. Il n\'avait pas l\'intention de devenir un skald lui-même, mais il pouvait et voulait parcourir de grandes distances pour écouter quelque chose de nouveau. Il ne détestait rien de plus que de faire de tels voyages ardus pour entendre exactement la même edda interprétée avec seulement de légères variations. Si le problème était suffisamment grave, le Deathmaster prenait les choses en main.</div>', 'fDeathmaster.jpg', 1, 28),
(44, 'Docteur Stormcrow', '<div><em>\"Une infection des plus remarquables.\"</em><br><br>Le Docteur Stormcrow est dans ce combat pour la recherche. Expert de toutes les formes de maladies infectieuses existantes, la virulence de la peste zombie le stupéfie par sa beauté sordide. Il est convaincu que si la magie est au cœur de l\'épidémie initiale, la propagation ultérieure de l\'infection est entièrement naturelle. Il cite comme sources la mort rampante et le flux sanglant (qui ont tué des centaines de milliers de personnes lorsqu\'ils n\'ont pas été contrôlés), en plus de l\'absence totale d\'émanations magiques chez la plupart des zombies mobiles. S\'il peut prouver ses théorèmes (et développer un remède), peut-être les nécromanciens pourront-ils être privés de leurs hordes apparemment illimitées.</div>', 'fDoctor-Stormcrow.jpg', 1, 20),
(45, 'Earl Jaimie', '<div><em>\"Toutes les grandes histoires doivent avoir une fin. Laissez-moi vous dire ce qui se passe !\"</em><br><br>Le comte Jaimie était un riche noble de cette lointaine (et étrangement nommée) terre de Dhüm. Il a voyagé dans le monde entier, collectionnant les livres et les histoires, regardant les spectacles de mummer et les pièces de théâtre, et il aime particulièrement les énigmes. Malheureusement, il aime aussi en partager la fin avec quiconque l\'écoute, d\'où son titre quelque peu ignominieux. Aujourd\'hui, piégé dans l\'Ouest par la peste noire et la marée verte qui menacent de submerger l\'humanité, Earl Jaimie se bat aux côtés de ses compagnons d\'infortune. Il aimerait seulement savoir comment cela va se terminer.</div>', 'fEarlJaimie.jpg', 1, 32),
(46, 'Finarton', '<div><em>\"Nous avons tué tous nos sorciers pour une bonne raison. Maintenant je dois nettoyer tout ça !\"</em><br><br>Finarton est grincheux. Il aime ses montagnes. Il aime sa solitude. Mais surtout, il aime la paix et le calme. La peste noire (et maintenant la horde verte) lui a apporté tout sauf ça. Les orcs étaient des voisins bruyants pour commencer, et maintenant ils recherchent la chair vivante jour et nuit. Si Finarton a une chose, c\'est beaucoup de chair vivante. La société géante n\'a pas de sorciers après un incident similaire dans un passé lointain, dont on ne se souvient que par tradition orale parmi le peuple géant. Il suggère que l\'humanité utilise sa propre méthode de prévention plutôt drastique.</div>', 'fFinarton.jpg', 4, 50),
(47, 'Fylguria', '<div><em>\"La nature rugit de fureur contre ces abominations. Je suis sa voix.\"</em><br><br>Alors que les grands seigneurs elfes débattent toujours de leur participation à la guerre contre la peste noire, les ordres druidiques ont entendu l\'agonie de la terre sous le pas des morts-vivants, et Fulgyria a répondu. Sa maîtrise des éléments naturels fait d\'elle une force inarrêtable et une alliée puissante contre la horde verte. Elle regrette seulement que son ordre n\'ait pas réagi plus tôt, car la magie nécromantique sape les énergies naturelles qu\'elle convoque pour les combattre. Pourtant, plus la bataille prend de l\'ampleur, plus la puissance de la tempête augmente.</div>', 'fFylguria.jpg', 2, 25),
(48, 'Gannicus', '<div><em>\"On ne mord pas. C\'est un mauvais esprit sportif.\"</em><br><br>Le gladiateur connu sous le nom de Gannicus s\'est fait un nom dans les fosses. Il a pris à cœur la maxime selon laquelle les guerriers font de leurs armes une partie de leur corps. Ainsi, bien qu\'il puisse utiliser à peu près n\'importe quelle lame, il choisit ses poings chaque fois que c\'est possible. Dans sa longue carrière, Gannicus est resté invaincu. En fait, il était à quelques jours du plus grand combat de sa vie lorsque la horde verte est arrivée. Il déchaîne sa fureur sur la menace zombie à chaque fois que c\'est possible. Il suffit de le mettre à la portée d\'un nécromancien pour voir ce qui se passe.</div>', 'fGannicus.jpg', 1, 30),
(49, 'Grayson Grüber', '<div><em>\"Nous combattons ce qui n\'est pas fixé, qui mute, et qui est finalement indestructible.\"</em><br><br>Il y a peu de sorciers aussi redoutables que Grayson Grüber dans la bataille contre la horde verte. Sa maîtrise de la magie destructrice dépasse celle des élémentalistes de plusieurs années son aînés. Là où il passe, des zombies carbonisés, gelés ou désintégrés jonchent son sillage. Malheureusement, il y a peu de sorciers aussi sombres et lugubres. Malheureusement, lorsque la peste noire a frappé, Grüber était loin de la capitale, et son amour de longue date (et non partagé) a été perdu dans l\'invasion initiale. Cependant, même si Grüber pense que leur cause est condamnée, il se battra jusqu\'à son dernier souffle au nom de la vengeance.</div>', 'fGrayson.jpg', 1, 20),
(50, 'Hitch le barde', '<div><em>\"Danse pour moi.\"</em><br><br>Hitch est un courtisan aux bords tranchants - une langue acérée, un esprit vif, un sens aigu de la mode et des lames acérées. Il a toujours été plus connu pour sa grâce sur la piste de danse et ses tournures de phrases lapidaires que pour ses prouesses martiales, mais c\'est ainsi qu\'il le souhaitait. Il était facile pour lui de se prélasser au centre de ses compagnons et de ses amis, de se moquer des seigneurs et des dames et de gronder leur mode démodée. Facile pour les nécromanciens de sous-estimer ce bel homme - jusqu\'à ce qu\'il mette en pièces leurs jouets, aussi gracieusement qu\'il valse.</div>', 'fHitch.jpg', 1, 20),
(51, 'Hyg', '<div><em>\"Raid à l\'ouest, j\'ai dit. Trouver de grandes richesses, j\'ai dit. Bah ! Ne lui dis pas, mais j\'aurais dû écouter ma femme.\"</em><br><br>Mari de Hyld, et chef de guerre de son clan, Hyg a longuement et éloquemment plaidé pour le droit d\'explorer les terres à l\'ouest des grandes montagnes, ayant découvert des chemins cachés à travers leurs hauteurs inhospitalières. Pourtant, quand ils sont arrivés, qu\'a trouvé son groupe ? Des zombies ! Des zombies orques, rien que ça ! Hyg et Hyld sont les seuls survivants de la puissante troupe d\'autrefois, et ils souhaitent désespérément rentrer chez eux, craignant les ravages que la peste noire a pu causer en leur absence.</div>', 'fHyg.jpg', 1, 35),
(52, 'Hyld', '<div><em>\"Raid à l\'ouest, il a dit. Trouver de grandes richesses, il a dit. Ce gros balourd poilu n\'écoute jamais !\"</em><br><br>Épouse d\'Hyg, et demoiselle de bouclier d\'une remarquable habileté, Hyld s\'opposa aux désirs de son mari de faire des raids vers l\'ouest, à travers les grandes montagnes. Outre la saison tardive et la menace des premières neiges, Hyld avait la vision d\'une grande obscurité balayant le monde. Naturellement, et à sa grande tristesse, Hyg a rejeté cette vision comme une absurdité. Depuis, il lui a présenté ses excuses à genoux, ce qui serait très bien s\'ils n\'étaient pas complètement encerclés par des zombies orcs. Maintenant, ils se battent pour rentrer chez eux, craignant le pire.</div>', 'fHyld.jpg', 1, 36),
(53, 'Jeanne', '<div><em>\"Coupez la tête et le corps meurt. Du moins, c\'est comme ça que ça marchait avant.\"</em><br><br>Jeanne a combattu les orcs depuis qu\'elle a rejoint l\'armée. Elle a prouvé sa valeur dans les raids et les escarmouches, les batailles et la guerre. Elle pensait vraiment avoir vu le pire que les orcs pouvaient offrir. Elle avait tort. Son régiment a été le premier à être frappé par la Horde Verte, et elle a été la seule survivante, grâce à un peu de chance et beaucoup d\'habileté au sabre. Elle a vite compris que si les orcs faisaient de puissants zombies, ils étaient encore plus stupides qu\'avant. Frapper les nécromanciens qui manipulent leurs marionnettes était le meilleur moyen de couper leurs ficelles.</div>', 'fJeanne.jpg', 1, 34),
(54, 'Kelsey', '<div><em>\"Je dis, seriez-vous un bon camarade et un canard ? Très aimable.\"<br>*BOOM!!*<br>\"Beaucoup mieux.\"</em><br><br>Quelque peu bavard et ridiculement formel à tout moment, Kelsey reste l\'un des plus grands élémentalistes que le royaume ait jamais connu. Feu, foudre, glace, ou terre... tous sont des outils dans les mains de Kelsey. Kelsey a déjà combattu sa part d\'orcs en temps de paix et en temps de guerre, et la peste noire n\'a pas changé grand-chose à ses yeux. Bien qu\'ils ne soient que des zombies stupides, il conseille la prudence. Les orcs ont toujours eu de grands nombres de leur côté, et la peste a fait ressortir tous leurs effectifs, pas seulement les guerriers. Ils sont plus nombreux que jamais.</div>', 'fKelsey.jpg', 1, 12),
(55, 'Lividia la cheffe de guerre', '<div><em>\"Ce n\'est pas mon sang.\"</em><br><br>La tribu nomade de Warchief Lividia habite les badlands poussiéreux et les déserts au nord-est des royaumes de l\'ouest, et a été parmi les premiers touchés par la Horde verte montante. Bien que l\'on puisse penser que les nomades sont relativement immunisés contre les hordes ambulantes qui se déplacent lentement, il n\'y a qu\'un nombre limité d\'oasis et de havres de paix dans les déserts, et tous ont été envahis. La chef Lividia (et son subordonné Tyro, un peu trop exubérant) se sont rendus dans les royaumes de l\'ouest, pour les trouver dans une situation encore plus désespérée. Elle pense que sa lame est plus nécessaire ici, et espère retourner bientôt auprès de son peuple avec des alliés dans son dos.</div>', 'fLividia.jpg', 1, 30),
(56, 'Lorentz', '<div><em>\"Ne vous éloignez pas de la route à moins que je ne dise que c\'est sans danger.\"</em><br><br>Bien que ses manières soient quelque peu abruptes et qu\'il puisse manquer d\'empathie envers ses compagnons, Lorentz souhaite seulement qu\'ils restent en sécurité et hors de danger. Enfant, Lorentz s\'est entraîné avec son père pour devenir un chasseur et un bûcheron, et maintenant ces compétences ont été mises à l\'épreuve, en gardant les compagnons hors du chemin toujours plus large de la horde. Bien qu\'il soit le plus à l\'aise dans la nature, les compétences de Lorentz en matière de tir à l\'arc sont tout aussi efficaces pour abattre des orcs que du gibier. Il trouve généralement la plupart de la nourriture dont les compagnons ont besoin, bien que l\'obsession de Zee pour les pâtisseries le laisse perplexe.</div>', 'fLorentz.jpg', 1, 10),
(57, 'Comtesse Ordelia', '<div><em>\"Bien sûr que je me bats en talons. Bons seigneurs, utilisez vos yeux ! Je suis petite !\"</em><br><br>Malgré sa petite stature, la présence de la comtesse Ordelia peut remplir une pièce. Avant la peste noire, elle commandait des troupes sur le terrain pour combattre les hordes d\'orcs, et a remporté plus de victoires que de nombreux autres commandants réunis. Elle est réputée pour sa langue acérée et son esprit de rasoir, qui était redoutable pour ses ennemis à la cour et un plaisir pour ses amis partout. Aujourd\'hui, parmi les ruines de la civilisation, quand elle parle, les gens écoutent. Et s\'ils veulent échapper aux déprédations de la horde verte, elle est peut-être leur seul espoir.</div>', 'fOrdelia.jpg', 1, 12),
(58, 'Ayla', '<div><em>\"Mon peuple a un dicton : Ne tue pas si tu peux blesser. Mais, puisque les zombies sont déjà morts...\"</em><br><br>La princesse Ayla est originaire d\'une île lointaine qui est pratiquement un paradis utopique. Pourtant, alors que son peuple a longtemps évité tout contact avec le monde en général, la peste noire est une source d\'inquiétude pour tous les peuples libres. Ainsi, la princesse Ayla, leur plus puissante guerrière, prête sa lame contre la horde verte. En tant que vétéran de nombreuses batailles, elle conseille de frapper directement les nécromanciens derrière la peste. Les zombies sont dangereux, mais les esprits qui les contrôlent sont la vraie menace. Cependant, c\'est plus facile à dire qu\'à faire.</div>', 'fAyla.jpg', 1, 55),
(59, 'Rocco', '<div><em>\"Je n\'ai jamais compris le terme \'bullseye\'. Les taureaux sont faciles. Ils restent souvent plantés là.\"</em><br><br>L\'habileté de Rocco avec l\'arbalète (et l\'arc recourbé, et les couteaux de lancer, et même les pierres) lui a permis de survivre quand tant d\'autres sont tombés dans la vague initiale des zombies orques. Ayant grandi dans une troupe de mummers, il a découvert très tôt les joies du tir à l\'arc et du lancer de couteaux, et a fait preuve d\'une incroyable aptitude naturelle pour ces deux disciplines. Il regrette la Horde verte et la peste noire, bien que cela lui ait donné de nombreuses occasions de s\'entraîner. Il rêve souvent de réaliser un jour \" le tir le plus parfait de toute l\'histoire \", bien qu\'il soit assez vague quant à sa définition.</div>', 'fRocco.jpg', 1, 15),
(60, 'Ryan John', '<div><em>\"Mon art promeut la paix, la compréhension et la bonne volonté. Sauf pour les zombies. Non, ils doivent disparaître.\"</em><br><br>Ryan John était un brillant poète et écrivain dont les œuvres ont été jouées et récitées dans des palais, des domaines, des tavernes et des auberges de bord de route à travers le royaume. Outre l\'écriture, son autre passion était le maniement de l\'épée. Maintenant que la horde verte a frappé et que la peste noire balaie le pays, il constate que les survivants ont plus que jamais besoin de ses écrits édifiants, et de son épée plus qu\'il ne le souhaiterait. Pourtant, alors que sa formation initiale était destinée à l\'entraînement et au sport, le passage au statut de guerrier n\'a pas été une mince affaire.</div>', 'fRyan.jpg', 1, 30);
INSERT INTO `survivant` (`id`, `nom`, `description`, `image`, `race_id`, `puissance`) VALUES
(61, 'Scowl', '<div><em>\"Les nécromanciens font aussi des cauchemars. C\'est grâce à moi.\"</em><br><br>Scowl est un homme obsédé par l\'éradication de la menace zombie, plus que beaucoup d\'autres survivants. Il se repose à peine, mange à peine et ne parle que des moyens les plus rapides de vaincre les hordes de morts-vivants. Pour lui, tuer les zombies ne fait que traiter le symptôme. Pour vraiment endiguer la marée, les nécromanciens eux-mêmes doivent être détruits. Une de ses stratégies favorites consiste à traquer ces monstres jusqu\'à leurs repaires et sanctuaires. Bien que ceux-ci soient souvent remplis de serviteurs, de pièges et d\'autres horreurs, Scowl souligne que les nécromanciens y sont également piégés avec lui, un scénario cauchemardesque pour toute cabale.</div>', 'fScowl.jpg', 1, 30),
(62, 'Sigrun', '<div><em>\"Attends, ils sortent de leurs tombes ? Vous voulez dire que je vais pouvoir les tuer deux fois ! ?\"</em><br><br>Pour une femme de sang avec une hache à moudre, la peste noire frappant la horde verte n\'aurait pas pu être une plus grande bénédiction. Sigrun a combattu les orcs depuis son plus jeune âge. Lorsque sa tribu nomade a traversé sans le savoir le territoire des orcs, les peaux vertes sont descendues en masse et ont massacré tous ceux qu\'elles n\'ont pu capturer. Sigrun a fini par s\'échapper et a consacré sa vie à chasser et tuer les orcs partout où elle les trouvait. Bien que la peste noire soit une menace horrible, elle ne peut dissimuler un certain plaisir à les découper une seconde fois.</div>', 'fSigrun.jpg', 1, 30),
(63, 'Sir Schwarz', '<div><em>\"Papiers, s\'il vous plaît.\"</em><br><br>Sir Schwarz était autrefois le gardien des portes du palais. Il était réputé pour sa fermeté, ses prouesses en matière de combat, et son adhésion indéfectible à tous les ordres donnés. Ainsi, lorsque la horde verte est descendue sur la capitale, Sir Schwarz a gardé sa porte, et seulement sa porte. Le palais fut mis à sac par les trois autres portes, mais devant la herse orientale, un vaste monticule de cadavres de zombies servit de nouveau rempart. Certains pensent que Sir Schwarz est une sorte de golem. On ne le voit jamais sans son armure, il ne semble jamais dormir, et peut supporter des blessures vraiment choquantes sans débilité apparente.</div>', 'fSchwarz.jpg', 1, 30),
(64, 'Spearhead', '<div><em>\"Regardez-moi ! WOOO !!\"</em><br><br>Il a peut-être un vrai nom, ou peut-être pas, mais Fer de Lance est à la hauteur de son surnom. Peu de guerriers chevronnés semblent aussi prompts à se jeter dans la mêlée la plus dense sans se soucier de leur propre sécurité. En fait, le fer de lance est plus heureux lorsque d\'autres survivants sont présents pour assister à ses actes téméraires. Son peuple est composé de barbares qui parcouraient autrefois les déserts et les badlands au nord-est des royaumes de l\'Ouest, et ils ont donc été parmi les premiers touchés par la horde verte. Alors que certains survivent dans des poches isolées à travers les badlands, Fer de Lance et son chef ont voyagé vers l\'ouest à la recherche d\'alliés contre la horde. Hélas, ils n\'en ont trouvé que trop peu.</div>', 'fSpearhead.jpg', 1, 30),
(65, 'Le Grand Zanzibar', '<div><em>\"D\'un simple geste du poignet, je peux produire un type de magie qui donnera à ces nécromanciens une véritable crise cardiaque.\"</em><br><br>Les étonnants pouvoirs magiques de Zanzibar n\'étaient surpassés que par son sens du spectacle. Il était aussi à l\'aise pour divertir des corbeaux que pour gérer une bataille d\'ogres ou une attaque de dragons (et ces derniers faisaient tout un spectacle). On aurait pu penser que la peste noire aurait mis un frein à son moral, mais même sous pression et en essayant juste de se maintenir en vie, les pouvoirs de Zanzibar n\'ont rien perdu de leur flair. Le spectacle doit continuer, comme il aime à le dire. Alors que les nécromanciens veulent vivre pour toujours, Zanzibar veut juste devenir une légende.</div>', 'fZanzibar.jpg', 1, 15),
(66, 'Le marquis de Roger', '<div><em>\"Enfin, une forme d\'art où j\'excelle vraiment.\"</em><br><br>Peu de nobles ont encouragé l\'écriture, la musique, la mode, la sculpture et la peinture plus que le marquis de Roget (qui préférait être simplement appelé \"marquis\"). S\'il ne possédait lui-même que peu de ces talents, il avait un goût exquis dans tous les domaines, et les moyens de financer leurs créateurs. Non, le seul véritable talent que possédait le Marquis était le maniement de l\'épée. Le Marquis est l\'un des rares survivants de l\'aristocratie, entièrement grâce à son jeu de lame. Il parcourt aujourd\'hui le pays avec ses compagnons d\'infortune, à la recherche d\'un refuge sûr où les arts pourront s\'épanouir à nouveau.</div>', 'fMarquis-1.jpg', 1, 15),
(67, 'Thomas', '<div><em>\"Ironiquement, cela a rendu mon travail beaucoup plus simple.\"</em><br><br>Débusquer la sorcellerie, la magie noire et la nécromancie était autrefois le pain quotidien de Thomas. Il se sent un peu responsable de la montée de la peste noire, car prévenir une telle catastrophe est du ressort d\'un chasseur de sorcières. Cependant, elle a pris naissance loin, très loin de la civilisation, et Thomas a travaillé principalement dans les villes et les campagnes voisines. Pour l\'instant, il considère que sa tâche principale est de défendre les survivants contre cette vile marée verte nécromantique. Malgré leur grand nombre, les nécromanciens orques (et humains) envoient encore occasionnellement leurs agents dans les enclaves des survivants, et Thomas reste vigilant face à de telles menaces.</div>', 'fThomas.jpg', 1, 15),
(68, 'Ygraine, guerrière du clan du cheval', '<div><em>\"De bons chevaux de guerre seraient parfaits pour ça. Mais essayez de trouver des bêtes vivantes dans ce désert infesté de zombies.\"</em><br><br>Le peuple d\'Ygraine a longtemps eu une affinité avec les chevaux, et était connu pour élever les bêtes les plus fortes, les plus rapides et les plus nobles de tous les royaumes. Ygraine elle-même a participé à de nombreuses batailles, et était aussi à l\'aise en selle que sur ses deux pieds. Hélas, la peste noire a dispersé les grands troupeaux aux quatre vents, et le peuple d\'Ygraine avec eux. Elle se bat maintenant à pied aux côtés des autres survivants, et échangerait un royaume entier contre un cheval.</div>', 'fYgraine.jpg', 1, 15),
(69, 'Zee', '<div><em>\"Ils m\'ont appelé un prodige qui pourrait conquérir un royaume. Tout ce que je voulais vraiment, c\'était mes pâtisseries.\"<br></em><br>Les sorciers qui ont élevé Zee étaient de plus en plus étonnés par ses talents magiques innés. Il lui suffit de jeter un coup d\'œil sur le fonctionnement d\'un sort pour en saisir l\'essence, ce qui est vital pour le lancement de sorts. Cependant, si elle doit improviser, les résultats sont de gros maux de tête et des saignements de nez. Sa maîtrise naturelle de la sorcellerie a permis à son groupe hétéroclite de survivre à la horde verte bien plus longtemps qu\'on ne l\'aurait cru possible. En effet, le groupe serait perdu sans Zee.<br><br></div>', 'fZee.jpg', 1, 10),
(70, 'Lion-o', '<div>Il est le fils du roi Claudus et le frère de Tygra. En tant que Seigneur actuel des ThunderCats, Lion-O est un leader sans peur, prêt à se jeter dans la bataille, même si cela lui cause des ennuis. Il manie la puissante épée des Omens, l\'arme la plus puissante de la Troisième Terre.&nbsp;</div>', 'Lion-o.jpg', 7, 35),
(71, 'Félibelle', '<div>Félibelle est un membre des ThunderCats et le troisième à les rejoindre. C\'est une clerc dont les compétences tirent parti de son immense vitesse. Elle manie un bâton mais est également capable de se battre sans arme.</div>', 'Felibelle.jpg', 7, 34),
(72, 'Snarf', '<div>\"Snarf\" est une créature d\'origine et d\'espèce encore inconnues. Il accompagne Lion-O. Snarf harcèle souvent Lion-O pour qu\'il ne fasse pas ce qu\'il pense être dangereux. Pourtant, Snarf est resté fidèle à Lion-O, quels que soient les problèmes qu\'il rencontre.</div>', 'snarf.jpg', 7, 2),
(73, 'WilyKit', '<div>WilyKit et son frère errent souvent dans les rues, utilisant sa flupe pour distraire et hypnotiser les civils pendant que Wilykat leur vole de la nourriture et de l\'argent. Après la destruction de Thundera, elle et son frère se sont associés à Lion-O, Tygra et Cheetara en prétendant qu\'ils ne les suivaient pas, mais qu\'ils marchaient simplement devant eux.</div>', 'Willykit.jpg', 7, 5),
(74, 'WilyKat', '<div>WilyKat utilise ses mots pour distraire, tandis que WilyKit utilise son instrument de musique pour les hypnotiser. WilyKat vole ensuite de la nourriture et de l\'argent aux gens. Lui et sa sœur rêvent d\'économiser un jour assez d\'argent pour aller chercher une carte qui les mènera à la cité perdue de l\'or et des richesses, El-Dara, où, dit-il, \"les chats nous supplieront pour de l\'argent\".</div>', 'Willykat.jpg', 7, 5),
(75, 'Panthro', '<div>Panthro est un général du royaume de Thundera et un grand ami du roi Claudus. Dans le premier épisode, Grune dit qu\'il a été vaincu au combat. Plus tard, Grune fait apparaître Panthro comme monnaie d\'échange pour que Claudus se rende. Le roi Claudus finit par libérer Panthro de ses chaînes et, lorsqu\'il a le dos tourné, Panthro le poignarde dans le dos, le tuant. Peu après, il est révélé que c\'était en fait Mumm-Ra déguisé en Panthro.<br><br>Panthro (le vrai) apparaît pour la première fois pour sauver Lion-O et les autres ThunderCats. Il est le combattant le plus expérimenté du groupe, capable d\'abattre une escouade entière de lézards avec seulement ses nunchakus et ses compétences en arts martiaux.</div>', 'Panthros.jpg', 7, 38),
(76, 'Tygra', '<div>Tygra est le fils de Javan, le seul héritier survivant du clan du Tigre déchu. Il a été adopté par la famille royale de Thundera et est devenu prince lorsqu\'il était bébé ; actuellement, il est le frère adoptif aîné du prince Lion-O et le fils adoptif du roi Claudus. Après avoir survécu à la chute de Thundera, il a formé, avec les chats survivants, les nouveaux ThunderCats, dont il est le commandant en second. Si Lion-O venait à tomber ou à renoncer à son titre de roi, Tygra serait le prochain successeur des ThunderCats.</div>', 'Tygra.jpg', 7, 34),
(77, 'Jackalman', '<div>Jackalman est un membre des Jackalmen, dont il est également le chef. Comme le reste de son espèce, ce chacal humanoïde est originaire de la planète Plun-Darr.</div>', 'Jackalman.jpg', 8, 30),
(78, 'Slithe', '<div>Slithe est le commandant autoproclamé des Mutants, un groupe composé de Reptiliens, de Monkiens et de Jackalmen. Ses deux bras droits sont Monkian et Jackalman.</div>', 'Slithe.jpg', 8, 30);");

    $this->addSql("INSERT INTO `survivant_classe` (`survivant_id`, `classe_id`) VALUES
(1, 1),
(1, 2),
(1, 3),
(2, 1),
(2, 2),
(2, 3),
(2, 7),
(3, 1),
(4, 2),
(5, 1),
(6, 1),
(7, 2),
(8, 3),
(9, 1),
(10, 2),
(10, 3),
(11, 1),
(11, 2),
(12, 1),
(12, 7),
(13, 1),
(13, 7),
(14, 5),
(14, 7),
(15, 1),
(15, 2),
(15, 5),
(16, 1),
(16, 4),
(17, 1),
(17, 7),
(18, 3),
(19, 1),
(19, 5),
(20, 1),
(20, 3),
(20, 7),
(21, 2),
(22, 1),
(22, 2),
(22, 7),
(23, 2),
(24, 3),
(24, 5),
(25, 5),
(25, 7),
(26, 1),
(27, 1),
(28, 3),
(29, 2),
(30, 1),
(31, 1),
(31, 4),
(32, 2),
(32, 5),
(33, 1),
(34, 3),
(35, 1),
(36, 2),
(36, 4),
(37, 1),
(37, 7),
(38, 1),
(38, 4),
(39, 1),
(39, 5),
(40, 1),
(40, 4),
(41, 1),
(41, 2),
(41, 5),
(41, 6),
(42, 1),
(42, 4),
(43, 1),
(43, 6),
(44, 1),
(44, 2),
(44, 3),
(45, 2),
(46, 1),
(46, 6),
(47, 2),
(47, 5),
(47, 7),
(48, 1),
(49, 2),
(50, 1),
(50, 7),
(51, 1),
(51, 5),
(52, 1),
(52, 5),
(53, 1),
(53, 5),
(54, 2),
(55, 1),
(55, 2),
(55, 3),
(56, 3),
(57, 3),
(57, 5),
(58, 1),
(59, 3),
(60, 1),
(60, 6),
(61, 1),
(61, 7),
(62, 1),
(62, 7),
(63, 1),
(63, 4),
(64, 1),
(64, 3),
(64, 7),
(65, 2),
(66, 1),
(66, 6),
(67, 1),
(67, 2),
(67, 5),
(68, 1),
(69, 2),
(70, 1),
(70, 5),
(71, 1),
(71, 7),
(72, 5),
(72, 7),
(73, 3),
(73, 5),
(74, 3),
(74, 7),
(75, 1),
(75, 4),
(76, 2),
(76, 3),
(76, 5),
(77, 1),
(77, 3),
(78, 1),
(78, 3);");

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE survivant DROP FOREIGN KEY FK_526EE3F36E59D40D');
        $this->addSql('ALTER TABLE survivant_classe DROP FOREIGN KEY FK_F4F41F78E9AE49B');
        $this->addSql('ALTER TABLE survivant_classe DROP FOREIGN KEY FK_F4F41F788F5EA509');
        $this->addSql('DROP TABLE classe');
        $this->addSql('DROP TABLE race');
        $this->addSql('DROP TABLE survivant');
        $this->addSql('DROP TABLE survivant_classe');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
